Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String

Resources:
  DagsHubS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::cyberbullying-artifacts-victor-obi
              - arn:aws:s3:::cyberbullying-artifacts-victor-obi/*

Outputs:
  DagsHubS3PolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref DagsHubS3Policy