artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/ef3259cadb6b4a938276bfd94dd913b5/artifacts
end_time: 1770041318024
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: ef3259cadb6b4a938276bfd94dd913b5
run_name: '1'
run_uuid: ef3259cadb6b4a938276bfd94dd913b5
source_name: ''
source_type: 4
source_version: ''
start_time: 1770041318013
status: 3
tags: []
user_id: chidera
