artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/08e4a3ebed1f46d2aa3fef7ee10d62e5/artifacts
end_time: 1770040189753
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: 08e4a3ebed1f46d2aa3fef7ee10d62e5
run_name: fortunate-fly-62
run_uuid: 08e4a3ebed1f46d2aa3fef7ee10d62e5
source_name: ''
source_type: 4
source_version: ''
start_time: 1770040189724
status: 3
tags: []
user_id: chidera
