artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/1bc8dc48a693461cacdc57d1a45a19fe/artifacts
end_time: 1770041481243
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: 1bc8dc48a693461cacdc57d1a45a19fe
run_name: '8'
run_uuid: 1bc8dc48a693461cacdc57d1a45a19fe
source_name: ''
source_type: 4
source_version: ''
start_time: 1770041481232
status: 3
tags: []
user_id: chidera
