artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/1ca96b58cf7a4ab6ad9a8aa7e99e3330/artifacts
end_time: 1770045623961
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: 1ca96b58cf7a4ab6ad9a8aa7e99e3330
run_name: xgboost_best
run_uuid: 1ca96b58cf7a4ab6ad9a8aa7e99e3330
source_name: ''
source_type: 4
source_version: ''
start_time: 1770045604863
status: 4
tags: []
user_id: chidera
