artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/a143acf97d304c3ea6a0933edf8dd74e/artifacts
end_time: 1770038948879
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: a143acf97d304c3ea6a0933edf8dd74e
run_name: bright-hog-491
run_uuid: a143acf97d304c3ea6a0933edf8dd74e
source_name: ''
source_type: 4
source_version: ''
start_time: 1770038948849
status: 3
tags: []
user_id: chidera
