artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/88e059721d3b4deca3bdcebe176cb8ae/artifacts
end_time: 1770041847854
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: 88e059721d3b4deca3bdcebe176cb8ae
run_name: '8'
run_uuid: 88e059721d3b4deca3bdcebe176cb8ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1770041847836
status: 3
tags: []
user_id: chidera
