artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/f2d4bb72ae264b9f9a47454f1f2b0724/artifacts
end_time: 1770037603754
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: f2d4bb72ae264b9f9a47454f1f2b0724
run_name: logistic_reg_best
run_uuid: f2d4bb72ae264b9f9a47454f1f2b0724
source_name: ''
source_type: 4
source_version: ''
start_time: 1770037598571
status: 4
tags: []
user_id: chidera
