artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/e5100ea6b61f42cd880eed10a2fe3b01/artifacts
end_time: 1770041498066
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: e5100ea6b61f42cd880eed10a2fe3b01
run_name: '9'
run_uuid: e5100ea6b61f42cd880eed10a2fe3b01
source_name: ''
source_type: 4
source_version: ''
start_time: 1770041498053
status: 3
tags: []
user_id: chidera
