artifact_uri: s3://cyberbullying-artifacts-victor-obi/mlflow/48ece2ab9ec84152bc2b2893c7b5376c/artifacts
end_time: 1770041758228
entry_point_name: ''
experiment_id: '138410636173462509'
lifecycle_stage: active
run_id: 48ece2ab9ec84152bc2b2893c7b5376c
run_name: lightgbm_best
run_uuid: 48ece2ab9ec84152bc2b2893c7b5376c
source_name: ''
source_type: 4
source_version: ''
start_time: 1770041498070
status: 3
tags: []
user_id: chidera
